<?php
/**
 * Implements hook_theme()
 */
function d8_demo_theme() {
  $items = array(
    'd8_demo_content' => array(
      'variables' => array('items' => array()),
    ),
    'd8_demo_link' => array(
      'variables' => array('video_id' => NULL),
      'template' => 'd8-demo-link'
    ),
  );

  return $items;
}

/**
 * Theme callback fot d8_demo_content
 */
function theme_d8_demo_content($variables) {
  $output = '<h2> Rendering content using Drupal 8 demo Theme function.</h2>';
  $output .= '<ul>';
  foreach($variables['items'] as $item) {
    $output .= '<li>' . $item . '</li>';
  }
  $output .= '</ul>';

  return $output;
}

/**
 * Implements hook_permission
 */
function d8_demo_permission() {
  return array('Administer Drupal8 demo configuration' =>  array(
      'title' => t('Administer Drupal8 demo configuration'),
    ),
  );
}
